// <auto-generated />
using System;
using Guestbook.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Guestbook.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200603200803_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Guestbook.Models.Record", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RecordId");

                    b.ToTable("Records");

                    b.HasData(
                        new
                        {
                            RecordId = 1,
                            Comment = "first comment",
                            Country = "poland",
                            DatePosted = new DateTime(2020, 6, 3, 22, 8, 2, 964, DateTimeKind.Local).AddTicks(4868),
                            Email = "xxx@gmail.com",
                            Nick = "starczi"
                        },
                        new
                        {
                            RecordId = 2,
                            Comment = "second comment",
                            Country = "universe",
                            DatePosted = new DateTime(2020, 6, 3, 22, 8, 2, 970, DateTimeKind.Local).AddTicks(7936),
                            Email = "yyy@gmail.com",
                            Nick = "starczi1"
                        },
                        new
                        {
                            RecordId = 3,
                            Comment = "third comment",
                            Country = "europe",
                            DatePosted = new DateTime(2020, 6, 3, 22, 8, 2, 970, DateTimeKind.Local).AddTicks(8233),
                            Email = "zzz@gmail.com",
                            Nick = "starczi2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
